# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "common/src/server_repo/postgres_server_repo/schema.rs"
import_types = ["diesel::sql_types::*"]

[migrations_directory]
dir = "migrations"
