name: CI
on: [push, pull_request]

jobs:
  frontend-build_test:
    runs-on: ubuntu-latest
    container:
      image: node:19-slim
    defaults:
      run:
        working-directory: web/
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Push built files
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: web/build

  backend-build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Debug build
        working-directory: backend/
        run: cross build --target aarch64-unknown-linux-gnu

      - name: Test
        working-directory: backend/
        run: cross test --target aarch64-unknown-linux-gnu

      - name: Production build
        working-directory: backend/
        run: cross test --target aarch64-unknown-linux-gnu --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: smart-server
          path: backend/target/aarch64-unknown-linux-gnu/release/pv191-smart-home-server
